const TempPosters = [
    {
           src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
           alt:"Zack",
           title:"Zacl",
           subtitle:"english",
     },
     {
       src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
       alt:"Zack",
       title:"Zacl",
       subtitle:"english",
     },
     {
       src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
       alt:"Zack",
       title:"Zacl",
       subtitle:"english",
     },   
     {
       src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
       alt:"Zack",
       title:"Zacl",
       subtitle:"english",
     }, 
     {
       src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
       alt:"Zack",
       title:"Zacl",
       subtitle:"english",
     },
     {
       src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
       alt:"Zack",
       title:"Zacl",
       subtitle:"english",
     }, 
     {
       src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
       alt:"Zack",
       title:"Zacl",
       subtitle:"english",
     },
     {
       src:"https://in.bmscdn.com/discovery-catalog/events/tr:%E2%80%A6g,ox-322,oy-20/et00047164-sztaxpptsc-portrait.jpg",
       alt:"Zack",
       title:"Zacl",
       subtitle:"english",
     },
 ];

export default TempPosters;